views/bp_transactions.py
from flask import render_template, request, redirect, session, url_for, Blueprint, current_app
from controllers.database_transactions import Controller as dbTctrl
from controllers.database_users_auth import Controller as dbUA
from controllers.database_reports import Controller as dbR
from controllers.table_headers import Controller as tblCtrl
from controllers.transactions import Controller as trCtrl
from controllers.importer import Controller as impCtrl


# ASSIGNMENTS
bp_transactions = Blueprint('bp_transactions', __name__)
db = current_app.extensions['sqlalchemy']


## TRANSACTION ROUTES
# IMPORT FILE / IMPORTED
@bp_transactions.route('/imports', methods=['GET', 'POST'])
def imports():
    if not dbUA.user_auth_check():
        return redirect(url_for('bp_users.login', from_page=url_for('bp_transactions.imports')))
    else:
        if request.method == 'POST':
            impCtrl.run_importer(request)
        transaction_query = trCtrl.change_tf_format(dbTctrl.transaction_query_imported())
        table_header = tblCtrl.get_imported_th()
        return render_template('imports.html', logged=True, header_dict=table_header, transaction_list=transaction_query)


# DETAILS
@bp_transactions.route('/details', methods=['POST'])
def details():
    if not dbUA.user_auth_check():
        return redirect(url_for('bp_users.login', from_page=url_for('bp_transactions.details')))
    else:
        if request.method == 'POST':
            table_header = tblCtrl.get_transaction_th()
            transaction_query = trCtrl.change_tf_format(trCtrl.unpack_transactions(dbTctrl.transaction_query_detailed(request.values.get('tr_date'), False), 1))
            table_u_header = tblCtrl.get_uploader_th()
            table_u_query = trCtrl.change_tf_format(trCtrl.unpack_transactions(dbTctrl.transaction_query_detailed(request.values.get('tr_date'), False), 2))
        else:
            transaction_query = [[]]
            table_header = [[]]
            table_u_header = [[]]
            table_u_query = [[]]
        return render_template('details.html', logged=True, header_u_dict=table_u_header, user_list=table_u_query, header_dict=table_header, transaction_list=transaction_query)


# REPORTS
@bp_transactions.route('/reports', methods=['GET', 'POST'])
def reports():
    if not dbUA.user_auth_check():
        return redirect(url_for('bp_users.login', from_page=url_for('reports')))
    else:
        # GET HEADERS
        table_tr_header = tblCtrl.get_sus_tr_th()
        table_acc_header = tblCtrl.get_sus_acc_th()
        table_ag_header = tblCtrl.get_sus_ag_th()
        # QUERY DATES
        transaction_query = dbTctrl.transaction_query_imported()
        date_query = tblCtrl.get_date_tables(transaction_query)
        # GET REPORT
        if request.method == 'POST' and (request.form['Transações'] is not None or request.form['Transações'] != ""):
            transaction_query_1 = trCtrl.change_tf_format(trCtrl.unpack_transactions(dbR.get_suspicious_transactions(request.form['Transações']), 0))
            transaction_query_2 = trCtrl.change_tf_format(trCtrl.reorder_data(dbR.get_suspicious_accounts(request.form['Transações'])))
            transaction_query_3 = trCtrl.change_tf_format(trCtrl.reorder_data(dbR.get_suspicious_agencies(request.form['Transações'])))
        else:
            # GET EMPTY
            transaction_query_1 = []
            transaction_query_2 = []
            transaction_query_3 = []
        return render_template('reports.html', logged=True, date_list=date_query, header_dict_1=table_tr_header, header_dict_2=table_acc_header,
                                header_dict_3=table_ag_header, transaction_list_1=transaction_query_1, transaction_list_2=transaction_query_2,
                                transaction_list_3=transaction_query_3)

views/bp_users.py
from flask import render_template, request, redirect, session, flash, url_for, Blueprint, current_app
from controllers.database_users_query import Controller as dbUQ
from controllers.database_users_auth import Controller as dbUA
from controllers.database_users_cd import Controller as dbUCD
from controllers.table_headers import Controller as tblCtrl


# ASSIGNMENTS
bp_users = Blueprint('bp_users', __name__)
db = current_app.extensions['sqlalchemy']


## USER ROUTES
# LOGIN
@bp_users.route('/login')
def login():
    from_pg = request.args.get('from')
    if not dbUA.user_auth_check():
        return render_template('/login.html')
    else:
        return redirect(url_for('views.index'))


# AUTH
@bp_users.route('/auth', methods=['POST',])
def auth():
    login = dbUA.user_auth(request, True)
    if login:
        goto_page = request.form['from_page']
        return redirect(f'/{goto_page}')
    else:
        return redirect(url_for('bp_users.login'))


# LOGOUT
@bp_users.route('/logout')
def logout():
    dbUA.user_auth_logoff()
    return redirect(url_for('bp_users.login'))


# LIST/CREATE USERS
@bp_users.route('/users', methods=['GET', 'POST',])
def users():
    if not dbUA.user_auth_check():
        return redirect(url_for('views.index', from_page=url_for('bp_users.users')))
    else:
        test = ""
        if request.method == 'POST':
            user_query = dbUQ.user_query_one(request.form['email'])
            if len(user_query) == 0:
                test = dbUCD.user_create(request)
            else:
                print('User already exists!')
        users_query = dbUQ.user_query_list()
        user_header_dict = tblCtrl.get_users_th()
        return render_template('users.html', logged=True, users_list=users_query, header_dict=user_header_dict, test_mail=test)


# USER DETAILS
@bp_users.route('/user_details', methods=['GET', ])
def user_details():
    if not dbUA.user_auth_check():
        return redirect(url_for('views.index', from_page=url_for('bp_users.user_details')))
    else:
        user_query = dbUQ.user_query_one(request.values.get('user_data'))
        user_header_dict = tblCtrl.get_users_th()
        return render_template('user_details.html', logged=True, user_list=user_query, header_dict=user_header_dict)


# UPDATE USERS
@bp_users.route('/user_details_update', methods=['POST', ])
def user_details_update():
    if not dbUA.user_auth_check():
        return redirect(url_for('views.index', from_page=url_for('bp_users.user_details')))
    else:
        if request.method == 'POST':
            dbUCD.user_update(request)
        return redirect(url_for('bp_users.users', from_page=url_for('bp_users.user_details')))


# DELETE USERS
@bp_users.route('/user_delete', methods=['GET', 'POST', ])
def user_delete():
    if not dbUA.user_auth_check():
        return redirect(url_for('views.index', from_page=url_for('bp_users.user_details')))
    else:
        dbUCD.user_delete(request)
        return redirect(url_for('bp_users.users', from_page=url_for('bp_users.user_details')))

templates/details.html
{% extends "/parts/main.html" %}
{% block content %}

				<!-- Imported -->
					<section id="three" class="wrapper style3">
						<div class="inner">

							<!-- Details -->
								<h3>Detalhes da Importação</h3>
									<div class="table-wrapper">
										<table class="alt">
											<thead>
												<tr>
													{% for value in header_u_dict.values() %}
													<th>{{ value }}</th>
													{% endfor %}
												</tr>
											</thead>
											<tbody>
												<tr>
													{% for item in user_list[0] %}
													<td>{{ item }}</td>
													{% endfor %}
												</tr>
											</tbody>
										</table>
									</div>

							<!-- Trasações -->
								<h3>Transações Importadas</h3>
									<div class="table-wrapper">
										<table class="alt">
											<thead>
												<tr>
													{% for value in header_dict.values() %}
													<th>{{ value }}</th>
													{% endfor %}
												</tr>
											</thead>
											<tbody>
												{% for transaction in transaction_list %}
												<tr>
													{% for item in transaction %}
													<td>{{ item }}</td>
													{% endfor %}
												</tr>
												{% endfor %}
											</tbody>
										</table>
									</div>

						</div>
					</section>

{% endblock %}

templates/imports.html
{% extends "/parts/main.html" %}
{% block content %}


				<!-- Imported -->
					<section id="imported" class="wrapper style3">
						<div class="inner">
							<h3>Importações</h3>
							<div class="table-wrapper">
								<table class="alt">
									<thead>
										<tr>
											{% for value in header_dict.values() %}
											<th>{{ value }}</th>
											{% endfor %}
											<th>Detalhar</th>
										</tr>
									</thead>
									<tbody>
										{% for transaction in transaction_list %}
											<tr>
												<form method="POST" action="{{ url_for('bp_transactions.details', tr_date=transaction[0].transaction_date) }}">
													{% for key in header_dict.keys() %}
														<td>{{ transaction[0][key] }}</td>
													{% endfor %}
													<td><button class="button submit">Detalhar</button></td>
												</form>
											</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
						</div>
					</section>


				<!-- Import -->
					<section id="import" class="wrapper style2 fade-up">
						<div class="inner">
							<h2>Importar</h2>
							<div class="split style1">
								<section>
									<form method="POST" action="{{ url_for('bp_transactions.imports') }}" enctype="multipart/form-data">
										<div class="fields">
											<div class="field whole">
												<label for="name">Arquivo de Transações</label>
												<input type="file" name="file" id="file" accept=".csv|.txt|.xml|.json" />
											</div>
										</div>
										<ul class="actions">
											<li><button class="button submit">Fazer Upload</button></li>
										</ul>
									</form>
								</section>
							</div>
						</div>
					</section>


{% endblock %}

templates/index.html
{% extends "/parts/main.html" %}
{% block content %}

				<!-- Intro -->
					<section id="intro" class="wrapper style1 fullscreen fade-up">
						<div class="inner">
							<h1>Extrato e Relatório Financeiro</h1>
							<p>Esse sistema permite o upload de transações financeiras em formato CSV e XML,<br />
							além de produzir um relatório de risco sobre as movimentações.</p>
							<p>Para melhor uso desse sistema, leia as instruções no <a href="">github</a>.</p>
						</div>
					</section>

{% endblock %}

templates/login.html
{% extends "/parts/main.html" %}
{% block content %}

				<!-- Alerts -->
				{% with messages = get_flashed_messages() %}
					{% if messages %} 
						<ul id="messages" class="list-unstyled">
							{% for message in messages %}
								<li class="alert alert-success">{{ message }}</li>
							{% endfor %}
						</ul>
					{% endif %}
				{% endwith %}

				<!-- Login -->
					<section id="login" class="wrapper style2 fade-up">
						<div class="inner">
							<h2>Login de Usuários</h2>
							<div class="split style1">
								<section>
									<form method="post" action="{{ url_for('bp_users.auth') }}">
										<input type="hidden" name="from_page" value="{{ from_page }}" />
										<div class="fields">
											<div class="field whole">
												<label for="name">Usuário</label>
												<input type="text" name="username" id="username" />
											</div>
											<div class="field whole">
												<label for="name">Senha</label>
												<input type="password" name="password" id="password" />
											</div>
										</div>
										<ul class="actions">
											<li><a href="" class="button submit">Login</a></li>
										</ul>
									</form>
								</section>
							</div>
						</div>
					</section>

{% endblock %}

templates/reports.html
{% extends "/parts/main.html" %}
{% block content %}


			<!-- Date Selector -->
					<section id="date_selector" class="wrapper style3">
						<div class="inner">
							<form method="POST" action="{{ url_for('bp_transactions.reports') }}">
								<h3>Relatório de Transações Suspeitas</h3>
								<div class="col-12">
									<select id="demo-category" name="Transações">
										<option value="">Selecione uma data!</option>
										{% for date in date_list %}
										<option value="{{ date }}">{{ date }}</option>
										{% endfor %}
									</select>
								</div>
								<br>
								<button class="button submit">Gerar Relatório</button>
							</form>
						</div>
					</section>


			<!-- Report -->
				<section id="imported" class="wrapper style2">
					<div class="inner">
						<h3>Transações Suspeitas</h3>
						<div class="table-wrapper">
							<table class="alt">
								<thead>
									<tr>
										{% for value in header_dict_1.values() %}
										<th>{{ value }}</th>
										{% endfor %}
									</tr>
								</thead>
								<tbody>
									{% for transaction in transaction_list_1 %}
										<tr>
											{% for item in transaction %}
												<td>{{ item }}</td>
											{% endfor %}
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</section>


			<!-- Report -->
				<section id="imported" class="wrapper style1">
					<div class="inner">
						<h3>Contas Suspeitas</h3>
						<div class="table-wrapper">
							<table class="alt">
								<thead>
									<tr>
										{% for value in header_dict_2.values() %}
											<th>{{ value }}</th>
										{% endfor %}
									</tr>
								</thead>
								<tbody>
									{% for transaction in transaction_list_2 %}
										<tr>
											{% for item in transaction %}
												<td>{{ item }}</td>
											{% endfor %}
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</section>


			<!-- Report -->
				<section id="imported" class="wrapper style2">
					<div class="inner">
						<h3>Agências Suspeitas</h3>
						<div class="table-wrapper">
							<table class="alt">
								<thead>
									<tr>
										{% for value in header_dict_3.values() %}
										<th>{{ value }}</th>
										{% endfor %}
									</tr>
								</thead>
								<tbody>
									{% for transaction in transaction_list_3 %}
										<tr>
											{% for item in transaction %}
												<td>{{ item }}</td>
											{% endfor %}
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</section>


{% endblock %}

templates/user_details.html
{% extends "/parts/main.html" %}
{% block content %}


			<!-- Users -->
				<section id="user_details" class="wrapper style3">
					<div class="inner">
						<h3>Editar Usuário</h3>
						<div class="table-wrapper split style1">
							<table class="alt">
								<tbody>
									{% for user in user_list %}
									<tr>
										{% for key in header_dict.keys() %}
										<td>{{ user[0][key] }}</td>
										{% endfor %}
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</section>


			<!-- Edit -->
				<section id="login" class="wrapper style2 fade-up">
					<div class="inner">
						<h3>Editar Usuário</h3>
						<p>Deixe em branco os campos que não deseja editar.</p>
						<div class="split style1">
							<section>
								<form method="POST" action="{{ url_for('bp_users.user_details_update') }}">
									<input type="hidden" name="user_email" value="{{ user_list[0][0].email }}" />
									<input type="hidden" name="from_page" value="{{ from_page }}" />
									<div class="fields">
										<div class="field whole">
											<label for="name">Usuário</label>
											<input type="text" name="username" id="username" placeholder="{{ user_list[0][0].username }}" />
										</div>
										<div class="field whole">
											<label for="email">E-mail</label>
											<input type="email" name="email" id="email" placeholder="{{ user_list[0][0].email }}" />
										</div>
										<div class="field whole">
											<label for="new_password">Senha Nova</label>
											<input type="password" name="new_password" id="new_password" />
										</div>
										<div class="field whole">
											<button class="button submit">Editar</button>
										</div>
									</div>
								</form>
							</section>
						</div>
					</div>
				</section>


{% endblock %}

templates/users.html
{% extends "/parts/main.html" %}
{% block content %}


			<!-- Users -->
				<section id="three" class="wrapper style3">
					<div class="inner">
						<h3>Usuários</h3>
						<div class="table-wrapper">
							<table class="alt">
								<thead>
									<tr>
										{% for value in header_dict.values() %}
										<th>{{ value }}</th>
										{% endfor %}
									</tr>
								</thead>
								<tbody>
									{% for user in users_list %}
										<tr>
											{% for key in header_dict.keys() %}
												<td>{{ user[0][key] }}</td>
											{% endfor %}
											<td><a method="GET" href="{{ url_for('bp_users.user_details', user_data=user[0].email) }}" class="button small">Editar</a></td>
											<td><a method="POST" href="{{ url_for('bp_users.user_delete', user_data=user[0].email) }}" class="button small">Excluir</a></td>
										</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</section>


			<!-- Add -->
				<section id="login" class="wrapper style2 fade-up">
					<div class="inner">
						<h3>Adicionar Novo Usuário</h3>
						<div class="split style1">
							<form method="POST" action="{{ url_for('bp_users.users') }}">
								<input type="hidden" name="from_page" value="{{ from_page }}" />
								<input type="hidden" name="test_mail" value="{{ test_mail }}" />
									<div class="fields">
										<div class="field whole">
											<label for="name">Usuário</label>
											<input type="text" name="username" id="username" />
										</div>
										<div class="field whole">
											<label for="name">E-mail</label>
											<input type="email" name="email" id="email" />
										</div>
									</div>
									<ul class="actions">
										<button class="button submit">Criar</a>
									</ul>
							</form>
						</div>
					</div>
				</section>


{% endblock %}